### ISSUE TITLE
Tag a Release

### ISSUE THREAD

**Issue by DigitalInBlue** [hayguen/iowahills_dsp#1]
I am writing a port file for VCPKG to make this library easy to install with the VCPKG package manager.  However, I do need this repository tagged with a release.  I created a fork at https://github.com/DigitalInBlue/iowahills_dsp, and you can see how I tagged a release.  

My pull request with Microsoft to add this library to VCPKG is in process. I would greatly appreciate it if you could expedite tagging a release!

**Comment by hayguen** [comment]
just noticing your issue. what version or tag name would you suggest?
be aware, that most stuff isn't tested!

**Comment by DigitalInBlue** [comment]
I don't have a strong opinion, but if you could tag it v0.1.0, that would be enough to get the VCPKG portfile complete.

**Comment by hayguen** [comment]
Done so, yesterday
