### ISSUE TITLE
iowahills.com down since Sep 2021

### ISSUE THREAD

**Issue by FvMP** [hayguen/iowahills_dsp#2]
According to web.archive.org recordings, iowahills.com website has been closed in Sep 2021. All content is still available in WayBack Machine https://web.archive.org/web/20171110201917/http://iowahills.com/

Anyone knows about Daniel Klostermann?

**Comment by hayguen** [comment]
copied the link to wayback machine to the README.

my last contact (response from Daniel) was September 12, 2021.
it was the OK, that i put his sources to github.
